# Generated by Django 4.2.3 on 2023-11-17 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverBiospecimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biospecimen_id', models.CharField(max_length=7, unique=True)),
                ('biospecimen_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ChildBiospecimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField(default=django.utils.timezone.now)),
                ('biospecimen_id', models.CharField(max_length=7, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_date_time', models.DateTimeField(blank=True, null=True)),
                ('processed_date_time', models.DateTimeField(blank=True, null=True)),
                ('stored_date_time', models.DateTimeField(blank=True, null=True)),
                ('placed_in_formalin_date_time', models.DateTimeField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('number_of_tubes', models.IntegerField(blank=True, null=True)),
                ('number_of_cards', models.IntegerField(blank=True, null=True)),
                ('in_person_remote', models.CharField(choices=[('I', 'In Person'), ('R', 'Remote')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_number', models.CharField(choices=[('F', 'First'), ('S', 'Second'), ('T', 'Third'), ('EC', 'Early Childhood'), ('MC', 'Middle Childhood')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Declined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declined_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KitSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_sent_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_consent_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotCollected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_collected_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('C', 'Completed'), ('P', 'In Process'), ('N', 'Not Collected')], max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perinatal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Processed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('processed_date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('logged_date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Received',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('storage_location', models.CharField(max_length=255)),
                ('received_date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('logged_date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedWSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier', models.CharField(max_length=255)),
                ('shipping_number', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('shipped_date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('logged_date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippedECHO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipped_date_time', models.DateTimeField(blank=True, null=True)),
                ('logged_date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippedWSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipped_date_time', models.DateTimeField(blank=True, null=True)),
                ('number_of_tubes', models.IntegerField(blank=True, default=1, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=255, null=True)),
                ('logged_date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('courier', models.CharField(blank=True, choices=[('F', 'FedEx'), ('P', 'USPS'), ('U', 'UPS'), ('D', 'DHL')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'status',
            },
        ),
        migrations.CreateModel(
            name='Stored',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stored_date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('storage_location', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('logged_date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trimester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimester', models.CharField(choices=[('F', 'First'), ('S', 'Second'), ('T', 'Third')], max_length=1)),
            ],
        ),
    ]
