# Generated by Django 4.2.3 on 2023-11-17 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biospecimen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trimester',
            name='pregnancy_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.pregnancy'),
        ),
        migrations.AddField(
            model_name='stored',
            name='outcome_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biospecimen.outcome'),
        ),
        migrations.AddField(
            model_name='status',
            name='collected_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biospecimen.collected'),
        ),
        migrations.AddField(
            model_name='status',
            name='declined_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biospecimen.declined'),
        ),
        migrations.AddField(
            model_name='status',
            name='kit_sent_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biospecimen.kitsent'),
        ),
        migrations.AddField(
            model_name='status',
            name='no_consent_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biospecimen.noconsent'),
        ),
        migrations.AddField(
            model_name='status',
            name='not_collected_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biospecimen.notcollected'),
        ),
        migrations.AddField(
            model_name='status',
            name='processed_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biospecimen.processed'),
        ),
        migrations.AddField(
            model_name='status',
            name='received_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biospecimen.received'),
        ),
        migrations.AddField(
            model_name='status',
            name='received_wsu_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biospecimen.receivedwsu'),
        ),
        migrations.AddField(
            model_name='status',
            name='shipped_echo_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biospecimen.shippedecho'),
        ),
        migrations.AddField(
            model_name='status',
            name='shipped_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biospecimen.shipped'),
        ),
        migrations.AddField(
            model_name='status',
            name='shipped_wsu_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biospecimen.shippedwsu'),
        ),
        migrations.AddField(
            model_name='status',
            name='stored_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biospecimen.stored'),
        ),
        migrations.AddField(
            model_name='shippedwsu',
            name='shipped_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipped',
            name='outcome_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biospecimen.outcome'),
        ),
        migrations.AddField(
            model_name='received',
            name='outcome_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biospecimen.outcome'),
        ),
        migrations.AddField(
            model_name='processed',
            name='outcome_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biospecimen.outcome'),
        ),
        migrations.AddField(
            model_name='perinatal',
            name='child_fk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='dataview.child'),
        ),
        migrations.AddField(
            model_name='perinatal',
            name='pregnancy_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.pregnancy'),
        ),
        migrations.AddField(
            model_name='collection',
            name='collection_number_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biospecimen.collectionnumber'),
        ),
        migrations.AddField(
            model_name='collection',
            name='collection_type_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='biospecimen.collectiontype'),
        ),
        migrations.AddField(
            model_name='collected',
            name='incentive_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dataview.incentive'),
        ),
        migrations.AddField(
            model_name='collected',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='childbiospecimen',
            name='age_category_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.agecategory'),
        ),
        migrations.AddField(
            model_name='childbiospecimen',
            name='child_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.child'),
        ),
        migrations.AddField(
            model_name='childbiospecimen',
            name='collection_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='biospecimen.collection'),
        ),
        migrations.AddField(
            model_name='childbiospecimen',
            name='incentive_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dataview.incentive'),
        ),
        migrations.AddField(
            model_name='childbiospecimen',
            name='status_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biospecimen.status'),
        ),
        migrations.AddField(
            model_name='caregiverbiospecimen',
            name='age_category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dataview.agecategory'),
        ),
        migrations.AddField(
            model_name='caregiverbiospecimen',
            name='caregiver_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.caregiver'),
        ),
        migrations.AddField(
            model_name='caregiverbiospecimen',
            name='collection_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='biospecimen.collection'),
        ),
        migrations.AddField(
            model_name='caregiverbiospecimen',
            name='incentive_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dataview.incentive'),
        ),
        migrations.AddField(
            model_name='caregiverbiospecimen',
            name='perinatal_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biospecimen.perinatal'),
        ),
        migrations.AddField(
            model_name='caregiverbiospecimen',
            name='project_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.project'),
        ),
        migrations.AddField(
            model_name='caregiverbiospecimen',
            name='status_fk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biospecimen.status'),
        ),
        migrations.AddField(
            model_name='caregiverbiospecimen',
            name='trimester_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biospecimen.trimester'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('collection_type_fk', 'collection_number_fk'), name='collection_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='childbiospecimen',
            constraint=models.UniqueConstraint(fields=('child_fk', 'collection_fk', 'age_category_fk'), name='child biospeciment unique constraint'),
        ),
        migrations.AddConstraint(
            model_name='caregiverbiospecimen',
            constraint=models.UniqueConstraint(fields=('caregiver_fk', 'collection_fk', 'trimester_fk'), name='caregiver_biospecimen_unique_constraint', violation_error_message="You can't have a duplicate item"),
        ),
    ]
