# Generated by Django 4.2.3 on 2023-09-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biospecimen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverbiospecimen',
            name='biospecimen_id',
            field=models.CharField(default='1111BS', max_length=7),
            preserve_default=False,
        ),
    ]
