# Generated by Django 4.2.3 on 2023-09-25 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biospecimen', '0002_caregiverbiospecimen_biospecimen_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='outcome_fk',
        ),
        migrations.AddField(
            model_name='processed',
            name='outcome_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='biospecimen.outcome'),
            preserve_default=False,
        ),
    ]
