# Generated by Django 4.2.3 on 2023-11-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biospecimen', '0003_alter_shippedwsu_shipped_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippedwsu',
            name='number_of_tubes',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
