# Generated by Django 4.2.3 on 2023-09-26 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biospecimen', '0003_remove_status_outcome_fk_processed_outcome_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processed',
            name='outcome_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biospecimen.outcome'),
        ),
    ]
