# Generated by Django 4.2.3 on 2023-11-25 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biospecimen', '0004_alter_shippedwsu_number_of_tubes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedMSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippedMSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipped_date_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='status',
            name='received_msu_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biospecimen.receivedmsu'),
        ),
        migrations.AddField(
            model_name='status',
            name='shipped_msu_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biospecimen.shippedmsu'),
        ),
    ]
