# Generated by Django 4.2.3 on 2023-09-26 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biospecimen', '0004_alter_processed_outcome_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiverbiospecimen',
            name='status_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biospecimen.status'),
        ),
    ]
