# Generated by Django 4.2.3 on 2023-09-26 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biospecimen', '0005_alter_caregiverbiospecimen_status_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='processed_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biospecimen.processed'),
        ),
    ]
