# Generated by Django 4.2.3 on 2023-09-27 13:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biospecimen', '0006_alter_status_processed_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiverbiospecimen',
            name='biospecimen_id',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.CreateModel(
            name='Stored',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stored_date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('storage_location', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('logged_date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('outcome_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biospecimen.outcome')),
            ],
        ),
    ]
