# Generated by Django 4.2.3 on 2023-09-27 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biospecimen', '0007_alter_caregiverbiospecimen_biospecimen_id_stored'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='stored_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biospecimen.stored'),
        ),
    ]
