# Generated by Django 4.2.3 on 2023-11-22 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiveraddress',
            name='eff_start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 9, 52, 18, 259306)),
        ),
    ]
