# Generated by Django 4.2.3 on 2023-07-27 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0002_caregiver_caregiver_project_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caregiver',
            old_name='caregiver_project_identifier',
            new_name='charm_project_identifier',
        ),
    ]
