# Generated by Django 4.2.3 on 2023-11-22 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0002_alter_caregiveraddress_eff_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiveraddress',
            name='eff_start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 10, 7, 5, 267064)),
        ),
    ]
