# Generated by Django 4.2.3 on 2023-07-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0003_rename_caregiver_project_identifier_caregiver_charm_project_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
