# Generated by Django 4.2.3 on 2023-07-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0004_caregiver_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='ewcp_participant_identifier',
            field=models.CharField(default='', max_length=16),
        ),
    ]
