# Generated by Django 4.2.3 on 2023-07-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0005_caregiver_ewcp_participant_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='participation_level_identifier',
            field=models.CharField(default='', max_length=2),
        ),
    ]
