# Generated by Django 4.2.3 on 2023-07-31 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0006_caregiver_participation_level_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='echo_pin',
            field=models.CharField(default='', max_length=3),
        ),
    ]
