# Generated by Django 4.2.3 on 2023-07-31 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0007_caregiver_echo_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiver',
            name='echo_pin',
            field=models.CharField(max_length=4),
        ),
    ]
