# Generated by Django 4.2.3 on 2023-07-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0008_alter_caregiver_echo_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='specimen_id',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='echo_pin',
            field=models.CharField(default='', max_length=3),
        ),
    ]
