# Generated by Django 4.2.3 on 2023-07-31 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0009_caregiver_specimen_id_alter_caregiver_echo_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('nick_name', models.CharField(max_length=255)),
                ('maiden_name', models.CharField(max_length=255)),
            ],
        ),
    ]
