# Generated by Django 4.2.3 on 2023-08-01 10:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0010_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.IntegerField(default=1)),
                ('status', models.CharField(default='C', max_length=1)),
                ('eff_start_date', models.DateTimeField()),
                ('eff_end_date', models.DateTimeField(default=datetime.datetime(2999, 12, 31, 0, 0))),
                ('caregiver_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.caregiver')),
                ('name_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.name')),
            ],
        ),
    ]
