# Generated by Django 4.2.3 on 2023-08-01 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0011_caregivername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregivername',
            name='eff_end_date',
            field=models.DateTimeField(default=datetime.datetime(2013, 11, 20, 20, 8, 7, 127325, tzinfo=datetime.timezone.utc)),
        ),
    ]
