# Generated by Django 4.2.3 on 2023-08-02 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0013_address_alter_caregivername_eff_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverAddressMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_move_date', models.DateField()),
                ('address_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.address')),
            ],
        ),
    ]
