# Generated by Django 4.2.3 on 2023-08-02 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0014_caregiveraddressmove'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaregiverAddressMove',
            new_name='AddressMove',
        ),
    ]
