# Generated by Django 4.2.3 on 2023-08-03 11:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0015_rename_caregiveraddressmove_addressmove'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaregiverEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('PR', 'Primary'), ('SD', 'Secondary'), ('IN', 'Inactive')], default='PR', max_length=2)),
                ('date_change', models.DateField(default=django.utils.timezone.now)),
                ('caregiver_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.caregiver')),
                ('email_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.email')),
            ],
        ),
    ]
