# Generated by Django 4.2.3 on 2023-08-04 11:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0016_email_caregiveremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.CharField(max_length=3)),
                ('phone_number', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='caregivername',
            name='status',
            field=models.CharField(choices=[('C', 'Current'), ('A', 'Archived')], default='C', max_length=1),
        ),
        migrations.CreateModel(
            name='CaregiverPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.CharField(choices=[('PR', 'Primary'), ('SD', 'Secondary'), ('IN', 'Inactive')], default='PR', max_length=2)),
                ('date_change', models.DateField(default=django.utils.timezone.now)),
                ('caregiver_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.caregiver')),
                ('phone_number_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.phone')),
            ],
        ),
    ]
