# Generated by Django 4.2.3 on 2023-08-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0017_phone_alter_caregivername_status_caregiverphone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caregiverphone',
            old_name='phone_number_fk',
            new_name='phone_fk',
        ),
    ]
