# Generated by Django 4.2.3 on 2023-08-07 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0019_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_user_name', models.CharField(max_length=255)),
                ('social_media_consent', models.BooleanField(default=True)),
                ('caregiver_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.caregiver')),
                ('social_media_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.socialmedia')),
            ],
        ),
    ]
