# Generated by Django 4.2.3 on 2023-08-07 19:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0021_alter_caregiversocialmedia_social_media_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverPersonalContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caregiver_contact_type', models.CharField(choices=[('PR', 'Primary'), ('SD', 'Secondary'), ('IN', 'Inactive')], default='PR', max_length=2)),
                ('date_change', models.DateField(default=django.utils.timezone.now)),
                ('address_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.address')),
                ('caregiver_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.caregiver')),
                ('email_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.email')),
                ('name_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.name')),
                ('phone_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.phone')),
            ],
        ),
    ]
