# Generated by Django 4.2.3 on 2023-08-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0022_caregiverpersonalcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
            ],
        ),
    ]
