# Generated by Django 4.2.3 on 2023-08-12 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0023_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_name', models.CharField(max_length=255)),
                ('project_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.project')),
            ],
        ),
    ]
