# Generated by Django 4.2.3 on 2023-08-12 23:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0024_survey'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incentive_type_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_outcome_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incentive_date', models.DateField(default=django.utils.timezone.now)),
                ('incentive_amount', models.IntegerField(null=True)),
                ('incentive_type_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.incentivetype')),
            ],
        ),
        migrations.CreateModel(
            name='CaregiverSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_completion_date', models.DateField(default=django.utils.timezone.now)),
                ('caregiver_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.caregiver')),
                ('incentive_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.incentive')),
                ('survey_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.survey')),
                ('survey_outcome_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.surveyoutcome')),
            ],
        ),
    ]
