# Generated by Django 4.2.3 on 2023-08-14 23:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0026_healthcarefacility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruitment_date', models.DateField(default=django.utils.timezone.now)),
                ('interviewer_comment', models.TextField()),
                ('caregiver_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.caregiver')),
                ('healthcare_facility_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.healthcarefacility')),
                ('incentive_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.incentive')),
            ],
        ),
    ]
