# Generated by Django 4.2.3 on 2023-08-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0027_recruitment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='interviewer_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
