# Generated by Django 4.2.3 on 2023-08-15 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0028_alter_recruitment_interviewer_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='caregiver_fk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='dataview.caregiver'),
        ),
    ]
