# Generated by Django 4.2.3 on 2023-08-15 11:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0030_consentversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_date', models.DateField(default=django.utils.timezone.now)),
                ('caregiver_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.caregiver')),
                ('consent_version_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.consentversion')),
            ],
        ),
    ]
