# Generated by Django 4.2.3 on 2023-08-16 11:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0031_consentcontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverSocialMediaHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_user_name', models.CharField(max_length=255)),
                ('social_media_consent', models.BooleanField(default=True)),
                ('revision_number', models.IntegerField()),
                ('revision_date', models.DateField(default=django.utils.timezone.now)),
                ('caregiver_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.caregiver')),
                ('caregiver_social_media_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.caregiversocialmedia')),
                ('social_media_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.socialmedia')),
            ],
        ),
    ]
