# Generated by Django 4.2.3 on 2023-08-16 11:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0032_caregiversocialmediahistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverAddressHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.IntegerField()),
                ('revision_date', models.DateField(default=django.utils.timezone.now)),
                ('address_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.address')),
                ('caregiver_address_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.caregiveraddress')),
                ('caregiver_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.caregiver')),
            ],
        ),
    ]
