# Generated by Django 4.2.3 on 2023-08-16 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0033_caregiveraddresshistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('caregiver_fk', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='dataview.caregiver')),
            ],
        ),
    ]
