# Generated by Django 4.2.3 on 2023-08-18 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0035_relation_nonmothercaregiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiversocialmedia',
            name='social_media_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.socialmedia'),
        ),
    ]
