# Generated by Django 4.2.3 on 2023-08-23 23:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0036_alter_caregiversocialmedia_social_media_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_type', models.CharField(max_length=255)),
                ('collection_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CaregiverBiospecimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biospecimen_date', models.DateField(default=django.utils.timezone.now)),
                ('caregiver_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.caregiver')),
                ('collection_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.collection')),
                ('incentive_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.incentive')),
                ('status_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.status')),
            ],
        ),
    ]
