# Generated by Django 4.2.3 on 2023-08-25 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0037_collection_status_caregiverbiospecimen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregiverbiospecimen',
            name='collection_fk',
        ),
    ]
