# Generated by Django 4.2.3 on 2023-08-25 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0038_remove_caregiverbiospecimen_collection_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverbiospecimen',
            name='collection_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dataview.collection'),
            preserve_default=False,
        ),
    ]
