# Generated by Django 4.2.3 on 2023-08-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0039_caregiverbiospecimen_collection_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
