# Generated by Django 4.2.3 on 2023-08-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0041_alter_caregiver_charm_project_identifier_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='address',
            name='address_not_unique',
        ),
        migrations.RemoveConstraint(
            model_name='caregivername',
            name='name_and_status_not_unique',
        ),
        migrations.AlterField(
            model_name='consentversion',
            name='consent_version',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='healthcarefacility',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='incentivetype',
            name='incentive_type_text',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='relation_type',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='social_media_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='surveyoutcome',
            name='survey_outcome_text',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('address_line_1', 'address_line_2', 'city', 'state', 'zip_code'), name='address_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='caregiveraddresshistory',
            constraint=models.UniqueConstraint(fields=('caregiver_address_fk', 'caregiver_fk', 'address_fk', 'revision_number'), name='caregiver_address_history_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='caregiverbiospecimen',
            constraint=models.UniqueConstraint(fields=('caregiver_fk', 'collection_fk'), name='caregiver_biospecimen_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='caregiveremail',
            constraint=models.UniqueConstraint(fields=('email_fk', 'caregiver_fk', 'email_type'), name='caregiver_email_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='caregivername',
            constraint=models.UniqueConstraint(fields=('name_fk', 'status', 'caregiver_fk'), name='caregiver_name_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='caregiverpersonalcontact',
            constraint=models.UniqueConstraint(fields=('caregiver_fk', 'name_fk'), name='caregiver_personal_contact_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='caregiverphone',
            constraint=models.UniqueConstraint(fields=('caregiver_fk', 'phone_fk', 'phone_type'), name='caregiver_phone_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='caregiversocialmedia',
            constraint=models.UniqueConstraint(fields=('caregiver_fk', 'social_media_fk', 'social_media_user_name'), name='caregiver_social_media_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='caregiversocialmediahistory',
            constraint=models.UniqueConstraint(fields=('caregiver_social_media_fk', 'caregiver_fk', 'social_media_fk', 'social_media_user_name', 'revision_number'), name='caregiver_social_media_history_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='caregiversurvey',
            constraint=models.UniqueConstraint(fields=('caregiver_fk', 'survey_fk'), name='caregiver_survey_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('collection_type', 'collection_number'), name='collection_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='consentcontract',
            constraint=models.UniqueConstraint(fields=('caregiver_fk', 'consent_version_fk'), name='consent_contract_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='incentive',
            constraint=models.UniqueConstraint(fields=('incentive_type_fk', 'incentive_date', 'incentive_amount'), name='incentive_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='nonmothercaregiver',
            constraint=models.UniqueConstraint(fields=('caregiver_fk', 'relation_fk'), name='non_mother_caregiver_unqiue_constraint'),
        ),
        migrations.AddConstraint(
            model_name='phone',
            constraint=models.UniqueConstraint(fields=('area_code', 'phone_number'), name='phone_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='recruitment',
            constraint=models.UniqueConstraint(fields=('caregiver_fk', 'healthcare_facility_fk'), name='recruitment_unique_constraint'),
        ),
    ]
