# Generated by Django 4.2.3 on 2023-09-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0043_remove_incentive_incentive_unique_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='caregiverbiospecimen',
            name='caregiver_biospecimen_unique_constraint',
        ),
        migrations.AddConstraint(
            model_name='caregiverbiospecimen',
            constraint=models.UniqueConstraint(fields=('caregiver_fk', 'collection_fk'), name='caregiver_biospecimen_unique_constraint', violation_error_message="You can't have a duplicate item"),
        ),
    ]
