# Generated by Django 4.2.3 on 2023-09-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0044_remove_caregiverbiospecimen_caregiver_biospecimen_unique_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='incentive',
            name='incentive_unique_constraint',
        ),
    ]
