# Generated by Django 4.2.3 on 2023-09-04 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0045_remove_incentive_incentive_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiverbiospecimen',
            name='incentive_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dataview.incentive'),
        ),
        migrations.AlterField(
            model_name='caregiversurvey',
            name='incentive_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dataview.incentive'),
        ),
    ]
