# Generated by Django 4.2.3 on 2023-09-05 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0047_primarycaregiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type_text', models.CharField(choices=[('MTHRUR', 'Mother Urine'), ('MTHRBLD', 'Mother Blood'), ('MTHRPLCNT', 'Mother Placenta')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ConsentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caregiver_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.caregiver')),
                ('consent_type_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.consenttype')),
            ],
        ),
    ]
