# Generated by Django 4.2.3 on 2023-09-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0048_consenttype_consentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentitem',
            name='consent_boolean',
            field=models.BooleanField(default=True),
        ),
    ]
