# Generated by Django 4.2.3 on 2023-09-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0049_consentitem_consent_boolean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consenttype',
            name='consent_type_text',
            field=models.CharField(choices=[('MTHR_UR', 'Mother Urine'), ('MTHR_BLD', 'Mother Blood'), ('MTHR_PLCNT', 'Mother Placenta'), ('MTHR_NL_HR_UR', 'Mother Nail Hair Urine'), ('BIRTH_CERT', 'Birth Certificate'), ('MDHHS', 'Michigan Department of Health and Human Services'), ('CHLD_POOP', 'Child Poop'), ('CHLD_TEETH', 'Child Teeth'), ('SRV_HOME', 'Serve Home'), ('ADDRS_B', 'Address B'), ('CHILD_BLD', 'Child Blood'), ('INFO_SHARE', 'Information Sharing'), ('ADDRESS', 'Address'), ('DNA', 'DNA'), ('OTH_STUDY', 'Other Study'), ('UOFM', 'University of Michigan'), ('SCL_MEDIA', 'Social Media')], max_length=20),
        ),
    ]
