# Generated by Django 4.2.3 on 2023-09-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0050_alter_consenttype_consent_type_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(null=True)),
                ('birth_sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('child_interviewer_comments', models.TextField()),
                ('birth_hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.healthcarefacility')),
                ('primary_care_giver_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.primarycaregiver')),
            ],
        ),
    ]
