# Generated by Django 4.2.3 on 2023-09-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0051_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='charm_project_identifier',
            field=models.CharField(default='0000M1', max_length=8),
            preserve_default=False,
        ),
    ]
