# Generated by Django 4.2.3 on 2023-09-08 23:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0052_child_charm_project_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='child_twin',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ChildName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('C', 'Current'), ('A', 'Archived')], max_length=1)),
                ('effective_start_date', models.DateField(default=django.utils.timezone.now)),
                ('effective_end_date', models.DateField(default=datetime.date(2099, 12, 31))),
                ('child_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.child')),
                ('name_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.name')),
            ],
        ),
    ]
