# Generated by Django 4.2.3 on 2023-09-11 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0054_primarycaregiver_primary_caregiver_row_has_two_primary_caregivers_or_none'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='charm_project_identifier',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.CreateModel(
            name='ChildAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.address')),
                ('child_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.child')),
            ],
        ),
        migrations.AddConstraint(
            model_name='childaddress',
            constraint=models.UniqueConstraint(fields=('child_fk', 'address_fk'), name='child address unique constraint'),
        ),
    ]
