# Generated by Django 4.2.3 on 2023-09-12 12:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0055_alter_child_charm_project_identifier_childaddress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_completion_date', models.DateField(default=django.utils.timezone.now)),
                ('child_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.child')),
                ('incentive_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dataview.incentive')),
                ('survey_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.survey')),
                ('survey_outcome_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.surveyoutcome')),
            ],
        ),
        migrations.CreateModel(
            name='ChildAddressHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.IntegerField(default=0)),
                ('revision_date', models.DateField(default=django.utils.timezone.now)),
                ('address_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.address')),
                ('child_address_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.childaddress')),
                ('child_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.child')),
            ],
        ),
        migrations.AddConstraint(
            model_name='childsurvey',
            constraint=models.UniqueConstraint(fields=('child_fk', 'survey_fk'), name='child survey unique constraint'),
        ),
        migrations.AddConstraint(
            model_name='childaddresshistory',
            constraint=models.UniqueConstraint(fields=('child_address_fk', 'child_fk', 'address_fk', 'revision_number'), name='child_address_history_unique_constraint'),
        ),
    ]
