# Generated by Django 4.2.3 on 2023-09-13 12:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0056_childsurvey_childaddresshistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assent_text', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChildAssent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assent_date', models.DateField(default=django.utils.timezone.now)),
                ('assent_boolean', models.BooleanField(default=True)),
                ('assent_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.assent')),
                ('child_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.child')),
            ],
        ),
        migrations.CreateModel(
            name='ChildAssentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assent_date', models.DateField(default=django.utils.timezone.now)),
                ('assent_boolean', models.BooleanField(default=True)),
                ('assent_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.assent')),
                ('child_assent_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.childassent')),
            ],
        ),
        migrations.AddConstraint(
            model_name='childassent',
            constraint=models.UniqueConstraint(fields=('child_fk', 'assent_fk'), name='child assent unique constraint'),
        ),
    ]
