# Generated by Django 4.2.3 on 2023-09-14 13:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0057_assent_childassent_childassenthistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_category', models.CharField(choices=[('EC', 'Early Childhood'), ('MC', 'Middle Childhood'), ('LC', 'Late Childhood')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ChildBiospecimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField(default=django.utils.timezone.now)),
                ('kit_sent_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('age_category_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.agecategory')),
                ('child_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.child')),
                ('collection_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.collection')),
                ('incentive_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dataview.incentive')),
                ('status_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataview.status')),
            ],
        ),
        migrations.AddConstraint(
            model_name='childbiospecimen',
            constraint=models.UniqueConstraint(fields=('child_fk', 'collection_fk', 'age_category_fk'), name='child biospeciment unique constraint'),
        ),
    ]
