# Generated by Django 4.2.3 on 2023-09-19 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0058_agecategory_childbiospecimen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicity', models.CharField(choices=[('H', 'Hispanic'), ('N', 'Non-Hispanic'), ('U', 'Unknown')], default='U', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(choices=[('I', 'American Indian or Alaska Native'), ('A', 'Asian'), ('B', 'Black or African American'), ('P', 'Native Hawaiian or Other Pacific Islander'), ('W', 'White'), ('U', 'Unknown')], default='U', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='caregiver',
            name='ethnicity_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dataview.ethnicity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caregiver',
            name='race_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dataview.race'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='ethnicity_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dataview.ethnicity'),
        ),
        migrations.AddField(
            model_name='child',
            name='race_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dataview.race'),
        ),
    ]
